### ISSUE TITLE
upgraded to 0.2.16 from 0.2.13 and ActiveScaffold breaks

### ISSUE THREAD

**Issue by levity** [jeffp/enumerated_attribute#10]
as of 0.2.13, ActiveScaffold was correctly showing my enums as dropdown menus -- with 0.2.16 they revert to displaying as text fields. Any idea why this might be?

**Comment by jeffp** [comment]
Hi Levity - by ActiveScaffold are you referring to Rails3?

**Comment by levity** [comment]
No, I'm on Rails 2.3.8, Ruby 1.8.7, and by ActiveScaffold I mean activescaffold.com

**Comment by jeffp** [comment]
Have you stepped through the code to find the reason?  You can still reload the older gem and compare the difference.  I believe there was a piece removed for compatibility with R3 and since there are no tests for this aspect, the bug likely slipped in.  If you fix the problem I can pull it in from your fork as long as the tests continue to pass.

**Comment by jeffp** [comment]
See Issue #8 - that describes what was removed, but I don't know if that is the problem.  If it is, we may have to re-add the fragment and check the rails version.

**Comment by turadg** [comment]
Closing since this sounds to have been fixed.
