### ISSUE TITLE
allows_nil? and allows_value? do not appear to be usable

### ISSUE THREAD

**Issue by unikitty37** [jeffp/enumerated_attribute#2]
This may well be my fault: these methods are in the code but not mentioned in the README.rdoc.

I'm trying to write an rspec test that will check an enum is not allowing nil. Using this definition
    enum_attr :country, %w{ England Scotland
      Wales Northern\ Ireland Channel\ Islands Isle\ of\ Man },
      :init => :England, :nil => false
and my reading of attribute_descriptor.rb suggests the test should be something like
    county.country.allows_nil?.should be_false
but I get
    NoMethodError in 'County should have a country'
    undefined method `allows_nil?' for :England:Symbol

I'm not sure whether these methods are supposed to be usable in this sort of case, though.

I guess this ticket is either "allows_nil? and allows_value? aren't available for use in tests" or "documentation does not show how to use allows_nil? and allows_value?" :)

**Comment by unikitty37** [comment]
Thinking about it, the issue is probably really that enumerated_attribute throws an exception if you set :nil => false and then try to set that field to nil; this makes writing tests difficult.

One workaround is something like
    lambda { @county.country = nil }.should raise_error(EnumeratedAttribute::InvalidEnumeration)
but this is ugly to say the least!

It would be better if it simply worked the same as other ActiveRecord validations and marked the record as invalid…

**Comment by charlesdeb** [comment]
I heartily agree with tinyclanger and would much prefer to be given an ActiveRecord invalid record error, rather than a ruby error when setting an enum_attr to nil. 

I have had to put your lambda example test into my tests - even for controllers when i am setting an enum_attr field to "". I'd much prefer to get a rails failed validation error, rather than the "EnumeratedAttribute::InvalidEnumeration" error that is currently thrown.
